### ISSUE TITLE
GitPod doesn't load beyond the homepage 

### ISSUE THREAD

**Issue by celeberr** [h-enk/doks#1263]
## Description

I have been running Doks using Gitpod while building a project so that development isn't done locally. 

Recently I wanted to add a number of docs and spun up gitpod again after a while.

The homepage on the local server loads but clicking on any link or viewing a new page fails to load.

### Steps to reproduce

Clone the repo using Gitpod open in VS code and try to view any page other than the homepage.

### Expected result

I should see my pages
 
### Actual result

<img width="574" alt="Screenshot 2024-07-30 at 14 11 16" src="https://github.com/user-attachments/assets/00ebabdf-81fc-49bd-a226-cbe64b19e8de">
<img width="574" alt="Screenshot 2024-07-30 at 14 11 23" src="https://github.com/user-attachments/assets/2db744e4-ef93-48ab-9171-2259746e4187">
<img width="493" alt="Screenshot 2024-07-30 at 14 11 59" src="https://github.com/user-attachments/assets/42d87b12-b58a-4412-acc5-4aaf4f1e3c75">
### Environment

Paste the information here as shown by `npm run info`

**Comment by h-enk** [comment]
Not sure what's wrong with your settings (it works allright with a clean install). 

Do you have set in `config/_default/hugo.toml`:

```toml
baseurl = "http://localhost/"
````

And, in `config/production/hugo.toml`:

```toml
baseurl = "/" # Or, your production URL
````

Does your `.gitpod.yml` look like:

````yml
# Source: https://github.com/gitpod-io/template-hugo/blob/main/.gitpod.yml

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
    - name: Run start up tasks
      before: brew install hugo
      init: pnpm install
      command: hugo server --baseURL $(gp url 1313) --liveReloadPort=443 --appendPort=false --bind=0.0.0.0 --disableFastRender --noHTTPCache --navigateToChanged

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
    - port: 1313
      onOpen: open-preview
````
