### ISSUE TITLE
Multiple hljs definitions in scss

### ISSUE THREAD

**Issue by OCram85** [h-enk/doks#392]
## Description

There is a `.hljs` definition in the `_code.scss` and `_syntax.scss ` file. Can the definition in `_code.scss` be removed?

Additionally I suggest following changes:

- `_snyntax.scss`

```scss
.hljs {
  display: block;
  overflow-x: auto;
  padding: 1.85rem 1.25rem;
  //background: $beige;
  //color: $body-color;
}
```

- increasing the padding to avoid overlapping the copy butting into the code content
- disabling the background / color properties to be able using the theme definitions like monokai from `./scss/app.scss`: highlight.js themes.
