### ISSUE TITLE
changeable global alerts

### ISSUE THREAD

**Issue by jeff-h** [h-enk/doks#585]
## Summary

My understanding is that once a user has dismissed the global alert once, their localStorage will record that fact forever. Therefore those users will never see global alerts in future, even if you wish to change the site alert at some point to contain something new. 

### Motivation

It would be great to be able to change the global alert and have the new version show again for all users.

One solution might be to supply an alert "id" which is used by `alert.js` instead of the hardcoded `announcement` constant. This would allow the site author to "reset" the global alert so that it shows even for users who previously hid it.

**Comment by h-enk** [comment]
Good one — thanks for pointing this out! Will think some things over + implement this.

**Comment by h-enk** [comment]
FYI — to be implemented — like so e,g,:

1. In `./config/_default/params.toml`, add `alertId`:

    ```toml
    # Alert
    alert = false
    alertId = "alert-1"
    alertDismissable = true
    # alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
    alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\">Check out Doks v0.2</a>"
    ```
2. In `./layouts/partials/header/alert.html`, add `data-id="{{ .Site.Params.alertId }}"`:

    ```html
    {{ if .Site.Params.alertDismissable -}}
      <div id="announcement" data-id="{{ .Site.Params.alertId }}" class="alert alert-primary alert-dismissible fade show d-none text-lg-center" role="alert">
        {{ .Site.Params.alertText | safeHTML }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {{ else -}}
      <div class="alert alert-primary text-center" role="alert">
        {{ .Site.Params.alertText | safeHTML }}
      </div>
    {{ end -}}
    ```
3. Update `./assets/js/alert.js`:

    ```js
    var announcement = document.getElementById('announcement');
    
    if (announcement !== null) {
      var id = announcement.dataset.id;
    
      if (localStorage.getItem(id) === null ) {
        announcement.classList.remove('d-none');
      }
    
      announcement.addEventListener('closed.bs.alert', () => {
        localStorage.setItem(id, 'closed');
      });
    }
    ```
