### ISSUE TITLE
Exclude individual pages from the search index

### ISSUE THREAD

**Issue by h-enk** [h-enk/doks#816]
For reference if interested, I've got a modified version of this which can exclude individual pages from  the index:

```yaml
---
title: "A Title"
description: "A Description"
lead: ""
date: 2022-03-20T12:52:27+11:00
draft: false
images: []
weight: 600
search:
  index: false
---
```
```js
  {{ $list := slice }}
  {{- if and (isset .Site.Params.options "searchsectionsindex") (not (eq (len .Site.Params.options.searchSectionsIndex) 0)) }}
  {{- if eq .Site.Params.options.searchSectionsIndex "ALL" }}
  {{- $list = .Site.Pages }}
  {{- else }}
  {{- $list = (where (where .Site.Pages "Type" "in" .Site.Params.options.searchSectionsIndex) ".Params.search.index" "!=" "false") }}
  {{- if (in .Site.Params.options.searchSectionsIndex "HomePage") }}
  {{ $list = $list | append .Site.Home }}
  {{- end }}
  {{- end }}
  {{- else }}
  {{- $list = (where .Site.Pages "Section" "docs") }}
  {{- end }}

  {{ $len := (len $list) -}}
```

_Originally posted by @james-d-elliott in https://github.com/h-enk/doks/issues/799#issuecomment-1168224086_
